services:
  mongo:
    image: 'mongo:latest'
    container_name: mongo_db
    restart: always
    env_file: ./.env
    ports:
      - "${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    image: 'locket-clone:latest'
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
                  "spring.data.mongodb.uri": "mongodb://admin:songtoan1910@13.239.54.49:27017/locket-clone?authSource=admin"
                }'

