services:
  mongo:
    image: 'mongo:latest'
    container_name: mongo_db
    restart: always
    env_file: ./.env
    ports:
      - "${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    image: 'locket-clone:latest'
    container_name: locket_clone
    restart: always
    env_file: ./.env
    volumes:
      - ./target:/app/target
    working_dir: /app
    entrypoint: [ "java", "-jar", "/app/target/locket-clone-0.0.1-SNAPSHOT.jar" ]
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring.data.mongodb.uri": "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo_db:27017/locket-clone?authSource=admin"
        }
    depends_on:
      - mongo

volumes:
  mongo_data:
    driver: local
