services:
  mongo:
    image: 'mongo:latest'
    container_name: mongo_db
    restart: always
    env_file: ./.env
    ports:
      - "${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    image: 'locket-clone:latest'
    container_name: locket_clone
    restart: always
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${SOCKET_IO_LOCAL_PORT}:${SOCKET_IO_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring.data.mongodb.uri": "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo_db:27017/locket-clone?authSource=admin"
        }
      FIREBASE_CONFIG_PATH: /app/firebase-credentials.json
    volumes:
      - /home/ec2-user/app/locket-clone/tuanisreal-memories-app-firebase-adminsdk-fbsvc-527ed77a14.json:/app/firebase-credentials.json
    depends_on:
      - mongo

volumes:
  mongo_data:
    driver: local
