services:
  app:
    build: .
    image: 'locket-clone:latest'
    env_file: ./.env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
                  "spring.data.mongodb.uri": "mongodb://admin:songtoan1910@13.239.54.49:27017/locket-clone?authSource=admin"
                }'

