spring:
  application:
    name: locket-clone
  data:
    mongodb:
      uri: mongodb://admin:songtoan1910@54.253.220.194:27017/locket-clone?authSource=admin
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB


server:
  port: 8080

security:
  jwt:
    secret: Y2JkN2M4NjU3NTM4Y2ZiNDEyMjU5NjM1ZGVhMDIwOGFiMzZiYjY0MTJmMDVlZTY3ZTQyMzZjMTA4YWIxODk3YzI4MTkxNTkzZjFmYmQ5ZGM5MTA1NmVmZjAyODExZTQxMGRlMWI1M2U5MDEzNDY1ZDJhMmZiODhmMDI0MWYyNWQ=
    # Token is valid 24 hours
    token-validity-in-seconds: 300
    refresh-token-validity-in-seconds: 900

aws:
  s3:
    region: ap-southeast-2
    bucketName: my-memories-bucket-1