name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "Setting up SSH Key..."
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.EC2_HOST}} >> ~/.ssh/known_hosts
          echo "SSH Key setup completed."

      - name: Deploy using Docker Compose
        run: |
          echo "Connecting to EC2 instance..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{secrets.EC2_HOST}} << 'EOF'
            echo "Starting installation of required packages..."
            sudo dnf install -y git docker
            sudo systemctl enable --now docker
            echo "Docker and Git installed successfully."
            echo "Downloading Docker Compose..."
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            export PATH=$PATH:/usr/local/bin
            echo "Docker Compose installed successfully."
            echo "Checking if the app directory is a Git repository..."
            # Kiểm tra thư mục có phải Git repo không
            if [ ! -d "/home/ec2-user/app/.git" ]; then
              echo "Cloning the repository..."
              rm -rf /home/ec2-user/app  # Xóa thư mục nếu có lỗi trước đó
              git clone https://github.com/PhamSongToan1910/locket.git /home/ec2-user/app
              echo "Repository cloned successfully."
            fi
            echo "Navigating to app directory and pulling the latest code..."
            cd /home/ec2-user/app/locket-clone
            git pull origin main
            echo "Git pull completed."
            echo "Building the application using Maven..."
            mvn clean install -DskipTests
            echo "Build completed successfully."
            echo "Stopping and removing old containers..."
            docker-compose down
            echo "Old containers stopped and removed."
            echo "Copying the .jar file into the app directory..."
            # Assuming your .jar file is in target/ directory after build
            cp /home/ec2-user/app/locket-clone/target/locket-clone-0.0.1-SNAPSHOT.jar /home/ec2-user/app/
            echo ".jar file copied successfully."
            echo "Rebuilding and starting containers..."
            docker ps
            docker-compose up -d --build
            docker ps
            echo "Containers started successfully."
          EOF
          echo "Deployment completed successfully."
