name: Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        shell: bash
  
      - name: Deploy using Docker Compose
        run: |
          echo "Connecting to EC2 instance..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} << EOF
            echo "Checking if the app directory is a Git repository..."
            if [ ! -d "/home/ec2-user/app/.git" ]; then
              echo "Cloning the repository..."
              rm -rf /home/ec2-user/app
              git clone https://github.com/PhamSongToan1910/locket.git /home/ec2-user/app
            fi
      
            echo "Pulling latest code..."
            cd /home/ec2-user/app/locket-clone && git pull --no-rebase
      
            echo "Stopping old containers..."
            cd /home/ec2-user/app/locket-clone && docker-compose down
      
            echo "Building the app..."
            cd /home/ec2-user/app/locket-clone && mvn clean install -DskipTests
      
            echo "Rebuilding and starting containers..."
            cd /home/ec2-user/app/locket-clone && docker-compose build --no-cache
            cd /home/ec2-user/app/locket-clone && docker-compose up -d
      
            echo "Done."
          EOF

          echo "Deployment completed successfully."
